import random

actions = [
    "Find",
    "Kill",
    "Defend",
    "Destroy",
    "Recover",
    "Rescue",
    "Capture",
    "Steal",
    "Escort",
    "Fetch",
    "Gather",
    "Deliver",
    "Investigate",
    "Watch",
    "Attack",
    "Hide",
    "Build",
    "Exterminate",
]


findArray = [
    ("Lost Pet", -30),
    ("Missing Person", -25),
    ("Lost Object", -20),
    ("Creature (CR 0-1)", -15),
    ("Safe Location", -10),
    ("Creature (CR 2-5)", 0),
    ("Very Rare Item", 5),
    ("Creature (CR + 1d12)", 0), # difficulty + 2CR
    ("Dangerous Location", 10),
    ("Legendary Item", 40),
]
# middle column not in yet
killArray = [
    ("CR 0-1", -40),
    ("CR 2", -30),
    ("CR 3", -20),
    ("CR 4", -10),
    ("CR 5", 0),
    ("CR 6-8", 10),
    ("Assassinate", 15),
    ("CR 9-10", 20),
    ("11 + 1d12", 0), # special
    ("Legendary Creature", 0), # special
]
defendArray = [
    ("Watch House", -50),
    ("Babysit", -40),
    ("Guard low importance item", -30),
    ("Shore up Military base", -20),
    ("Guard Person", -10),
    ("Guard semi-important item", 0),
    ("Defend Against Small Attack", 10),
    ("Guard Very Important Person/Item", 15),
    ("Defend Against Attack", 25),
    ("Defend Against Large Scale Attack", 40),
]
destroyArray = [
    ("Mundane Item", -50),
    ("Building", -40),
    ("Minor Criminal Organization", 0),
    ("Magic Item", 0),
    ("Minor Organization", 10),
    ("Criminal Organization", 15),
    ("Organization", 25),
    ("Major Criminal Organization", 30),
    ("Major Organization", 35),
    ("Legendary Item/Artifact", 50),
]
recoverArray = [
    ("Lost Item", -30),
    ("Stolen Mundane Item", -20),
    ("Mildly Valuable Item", -10),
    ("Stolen Magic Item", 0),
    ("Item lost in strange location", 10),
    ("Valuable Item", 15),
    ("Item lost in dangerous location", 20),
    ("Extremely high value item", 30),
    ("Item taken by powerful entity", 40),
    ("Legendary Item", 50),
]
rescueArray = [
    ("Cat in Tree", -80),
    ("Citizens Stranded", -20),
    ("Citizens Lost", -10),
    ("Citizens in dangerous location", 0),
    ("Adventures in dungeon", 10),
    ("Kidnapped Citizen", 15),
    ("Adventures in Underdark", 30),
    ("Hostage Situation Mid", 35),
    ("Very Dangerous Dungeon", 50),
    ("Extremely high profile hostage", 60),
]
captureArray = [
    ("Loose Pet", -50),
    ("CR 0-1 Beast", -30),
    ("CR 2-4 Creature", 0),
    ("Bandit Leader", 0),
    ("Outlaw", 0),
    ("Thief", 0),
    ("Political Opponent", 10),
    ("CR 5-10 Creature", 20),
    ("High Profile Criminal", 25),
    ("Legendary Creatrure", 60),
]
stealArray = [
    ("Minor Item", -20),
    ("Semi-Important Documents", 0),
    ("Normal Item", 0),
    ("Highly Important Document", 10),
    ("High Value Item", 15),
    ("Highly Guarded Item", 20),
    ("Item in Hostile Environment", 25),
    ("Item on Specific Perosn", 30),
    ("Item Owned by Legendary Creature", 60),
    ("Item in Different Plane", 70),
]
escortArray = [
    ("Guide Tourists", -35),
    ("Trasnport Materials", 0),
    ("Merchant Escort", 0),
    ("Diplomat Escort", 0),
    ("Important Person's Escort", 10),
    ("High Value Cargo", 15),
    ("Escort into Dangerous Area", 20),
    ("Escort through Hostile Area", 25),
    ("Targeted Individual", 30),
    ("Incredibly High-Value Person", 40),
]
fetchArray = [
    ("Herbs", -40),
    ("Mundane Items", -30),
    ("Shopping", -25),
    ("Necessities", 0),
    ("1d20 Common Materials (CR 1-4)", 0),
    ("1d12 Uncommon Materials (CR 5-8)", 10),
    ("1d10 Rare Materials (CR 9-12)", 30),
    ("1d8 Very Rare Materials (CR 13-16)", 40),
    ("1d20 Legendary Materials (CR 17-22)", 50),
    ("1d4 Mythic Materials (CR 22+)", 60),
]
gatherArray = [
    ("Farming Assistance", -50),
    ("Orchard Assistance", -50),
    ("Long Distance", 0),
    ("Difficult Area", 0),
    ("Dangerous Substance", 0),
    ("Dangerous Area", 10),
    ("Highly Uncomfortable Area", 10),
    ("Medium Value", 15),
    ("High Value", 25),
    ("Unique Materials",35),
]
# special (danger rating)
deliverArray = [
    ("0-10 Miles", 0),
    ("11-25 Miles", 5),
    ("26-100 Miles", 10),
    ("101-250 Miles", 15),
    ("251-500 Miles", 20),
    ("501-1000 Miles", 25),
    ("1001-2500 Miles", 30),
    ("2501-5000 Miles", 35),
    ("5001-10000 Miles", 40),
    ("Across Planes", 40),
]
investigateArray = [
    ("Animal Tracks", -40),
    ("Information Request", -30),
    ("Minor Crime", -20),
    ("Unknown Footsteps", -10),
    ("Organized Crime", 0),
    ("Mysterious Phenomenon", 0),
    ("Specific Person", 0),
    ("Serious Crime", 10),
    ("Strange Footprints", 15),
    ("High Profile Person", 25),
]
watchArray = [
    ("Someone's House", -50),
    ("Someone's Kid", -40),
    ("Specific Location", -30),
    ("Low Value Item", -20),
    ("Farm", -10),
    ("Business", 0),
    ("Mid Value Item", 0),
    ("Targeted Item", 10),
    ("High Value Item", 20),
    ("Priceless Item", 40),
]
attackArray = [
    ("Goblin Hideout", 0),
    ("Cult Base", 0),
    ("Minor Encampment", 0),
    ("Syndicate Base", 10),
    ("Cult Headquarters", 15),
    ("Military Encampment", 20),
    ("Major Syndicate Base", 30),
    ("High Importance Military Base", 40),
    ("Syndicate Headquarters", 50),
    ("Major City", 60),
]
hideArray = [
    ("Mundane Document", -30),
    ("Evidence", -10),
    ("Sensitive Documents", 0),
    ("Person", 0),
    ("Valuable Item", 0),
    ("Priceless Item", 10),
    ("Heavily-Targeted Person", 20),
    ("Treasure", 20),
    ("Very Important Item", 25),
    ("Clone", 30),
]
buildArray = [
    ("Simple Craft", -30),
    ("Small/Simple Building", -20),
    ("Medium/Simple Building", -10),
    ("Craft", 0),
    ("Large/Simple Building", 0),
    ("Building", 0),
    ("Complex Item", 10),
    ("Large Building", 10),
    ("Complex Building", 20),
    ("Highly Complex Item", 30),
]
exterminateArray = [
    ("Mole Infestation", -40),
    ("Rat Infestation", -40),
    ("Bee Hive", -40),
    ("Wolf Pack", -20),
    ("Wasp Infestation", -20),
    ("Ant Infestation",-10),
    ("Snake Infestation", 0),
    ("Cockroach Infestation", 0),
    ("Zombies", 10),
    ("Bullette Infestation", 20),
]



actionDictionary = {
    "Find": findArray,
    "Kill": killArray,
    "Defend": defendArray,
    "Destroy": destroyArray,
    "Recover": recoverArray,
    "Rescue": rescueArray,
    "Capture": captureArray,
    "Steal": stealArray,
    "Escort": escortArray,
    "Fetch": fetchArray,
    "Gather": gatherArray,
    "Deliver": deliverArray,
    "Investigate": investigateArray,
    "Watch": watchArray,
    "Attack": attackArray,
    "Hide": hideArray,
    "Build": buildArray,
    "Exterminate": exterminateArray,
}


rewardArray = [
    ("Copper", sum(random.randint(1, 12) for _ in range(2))),
    ("Silver", sum(random.randint(1, 12) for _ in range(2))),
    ("Silver", sum(random.randint(1, 12) for _ in range(4))),
    ("Gold", sum(random.randint(1, 12) for _ in range(1))),
    ("Gold", sum(random.randint(1, 12) for _ in range(2))),
    ("Gold", sum(random.randint(1, 12) for _ in range(3))),
    ("Gold", sum(random.randint(1, 12) for _ in range(4))),
    ("Platinum", sum(random.randint(1, 8) for _ in range(1))),
    ("Platinum", sum(random.randint(1, 10) for _ in range(2))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(3))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(4))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(5))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(8))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(10))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(12))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(15))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(18))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(21))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(25))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(30))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(50))),
    ("Platinum", sum(random.randint(1, 12) for _ in range(75))),
    ("Platinum", sum(random.randint(1, 20) for _ in range(100)))
]

specialRewardArray = [
    "Adventurer's Pack Item",
    "Explorer's Pack Item",
    "Dungeoneer's Pack Item",
    "Cantrip Spell Scroll",
    "2d12 + 1 Arrows",
    "Potion of Healing",
    "Level 1 Spell Scroll",
    "1 Common Item",
    "1 Common Item",
    "1 Common Item",
    "1 Uncommon Item",
    "1 Uncommon Item",
    "Rare Item",
    "1 Uncommon Item",
    "1 Rare Item",
    "1 Rare Item",
    "1 Very Rare Item",
    "1 Very Rare Item",
    "1 Very Rare Item",
    "Blessing",
    "Epic Boon",
    "Legendary Item",
    "Legendary Item"
]

feats = [
    "Alert",
    "Athlete",
    "Actor",
    "Charger",
    "Crossbow Expert",
    "Defensive Duelist",
    "Dual Wielder",
    "Dungeon Delver",
    "Durable",
    "Elemental Adept",
    "Grappler",
    "Great Weapon Master",
    "Healer",
    "Heavily Armored",
    "Heavy Armor Master",
    "Inspiring Leader",
    "Keen Mind",
    "Lightly Armored",
    "Linguist",
    "Lucky",
    "Mage SLayer",
    "Magic Initiate",
    "Martial Adept",
    "Medium Armor Master",
    "Mobile",
    "Moderately Armored",
    "Mounted Combatant",
    "Observant",
    "Polearm Master",
    "Resilient",
    "Ritual Caster",
    "Savage Attacker",
    "Sentinel",
    "Sharpshooter",
    "Shield Master",
    "Skilled",
    "Skulker",
    "Spell Sniper",
    "Tavern Brawler",
    "Tough",
    "War Caster",
    "Weapon Master",
    "Artificer Initiate (T)",
    "Chef (T)",
    "Crusher (T)",
    "Eldritch Adept (T)",
    "Fey Touched (T)",
    "Fighting Initiate (T)",
    "Gunner (T)",
    "Metamagic Adept (T)",
    "Piercer (T)",
    "Poisoner (T)",
    "Shadow Touched (T)",
    "SKill Expert (T)",
    "Slasher (T)",
    "Telekinetic (T)",
    "Telepathic (T)"
]

boons = [
    "Boon of Combat Prowess",
    "Boon of Dimensional Travel",
    "Boon of Fate",
    "Boon of Fortitude",
    "Boon of High Magic",
    "Boon of Immortality",
    "Boon of Invincibility",
    "Boon of Irresistible Offense",
    "Boon of Luck",
    "Boon of Magic Resistance",
    "Boon of Peerless Aim",
    "Boon of Perfect Health",
    "Boon of Planar Travel",
    "Boon of Quick Casting",
    "Boon of Recovery",
    "Boon of Resilience",
    "Boon of Skill Proficiency",
    "Boon of Speed",
    "Boon of Spell Mastery",
    "Boon of Spell Recall",
    "Boon of the Fire Soul",
    "Boon of the Night Spirit",
    "Boon of the Stormborn",
    "Boon of the Unfettered",
    "Boon of Truesight",
    "Boon of Undetectability"
]

races = [
    "Hill Dwarf",
    "Mountain Dwarf",
    "High Elf",
    "Wood Elf",
    "Drow",
    "Lightfoot Halfling",
    "Stout Halfling",
    "Human",
    "Human Variant",
    "Chromatic Dragonborn",
    "Metallic Dragonborn",
    "Forest Gnome",
    "Rock Gnome",
    "Half Elf",
    "Half Orc",
    "Tiefling",
]

classes = [
    "Barbarian",
    "Bard",
    "Cleric",
    "Druid",
    "Fighter",
    "Monk",
    "Paladin",
    "Ranger",
    "Rouge",
    "Sorcerer",
    "Warlock",
    "Wizard"
]

specialTraits = [
    "None",
    "Prime Race (2x)",
    "5 Feats",
    "Superior Feat (x5)",
    "3 Boons",
    "Superior Boon (x3)",
    "Prime Class (2x)",
    "Rare Magic Item",
    "Very Rare Magic Item"
]

specialSpecialTraits = [
    "3 Superior Feats",
    "2 Superior Boons",
    "Legendary Class (x3)",
    "Legendary Item",
    "Awakened Feat (x10)",
    "Awakened Boon (x6)",
    "Legendary Subclass (x5)",
    "1 Treasure",
    "High Value",
    "Highest Value"
]

artifacts = [
    "Book of Exalted Deeds",
    "Book of Vile Darkness",
    "Draakhorn",
    "Eye of Vecna",
    "Hand of Vecna",
    "Mask of the Dragon Queen",
    "Orb of Dragonkind",
    "Ring of Winter",
    "Staff of the Forgotten One",
    "Stone of Golorr",
    "Wand of Orcus",
    "Wyrmskull Throne",
    "Heart of the Ocean",
    "Longbow of Endless Frost",
    "Magma Armor of Creation",
    "Amulet of Eternal Flames",
    "Gauntlet of Ash",
    "Goblet of Ooze",
    "Insignia of Earth",
    "Ring of Endless Sky",
    "Baba Yaga’s Mortar and Pestle (T)",
    "Crook of Rao (T)",
    "Demonomicon of Iggwilv (T)",
    "Luba’s Tarokka of Souls (T)",
    "Mighty Servant of Leuk-o (T)",
    "Teeth of Dahlver-nar (T)"
]

legendaryItems = [
    "Apparatus of Kwalish",
    "Belt of Cloud Giant Strength",
    "Belt of Storm Giant Strength",
    "Black Dragon Mask",
    "Backstaff",
    "Blue Dragon Mask",
    "Cloak of Invisibility",
    "Crystal Ball of Mind Reading",
    "Crystal Ball of Telepathy",
    "Crystal Ball of True Seeing",
    "Cubic Gate",
    "Deck of Many Things",
    "Dragonstaff of Ahghairon",
    "Green Dragon Mask",
    "Holy Symbol of Ravenkind",
    "Horn of Valhalla, Iron",
    "Icon of Ravenloft",
    "Instrument of the Bards, Ollamh Harp",
    "Ious Stone, Greater Absorption",
    "Ioun Stone, Mastery",
    "Ioun Stone, Regeneration",
    "Iron Flask",
    "Lost Crown of Besilmer",
    "Red Dragon Mask",
    "Ring of Air Elemental Command",
    "Ring of Djinni Summoning",
    "Ring of Earth Elemental Command",
    "Ring of Fire Elemental Command",
    "Ring of Invisibility",
    "Ring of Spell Turning",
    "Ring of Three Wishes",
    "Ring of Water Elemental Command",
    "Robe of the Archmagi",
    "Rod of Lordly Might",
    "Rod of Resurrection",
    "Scarab of Protection",
    "Sovereign Glue",
    "Spell Gem, Diamond",
    "Spell Gem, Ruby",
    "Spell Gem, Star Ruby",
    "Spell Scroll, 9th Level",
    "Sphere of Annihilation",
    "Staff of the Magi",
    "Talisman of Pure Good",
    "Talisman of the Sphere",
    "Talisman of Ultimate Evil",
    "Tome of the Stilled Tongue",
    "Universal Solvent",
    "Well of Many Worlds",
    "White Dragon Mask",
    "Blood Fury Tattoo (T)"
]

veryRareItems = [
    "Amulet of the Black Skull",
    "Amulet of the Planes",
    "Bag of Devouring",
    "Belt of Fire Giant Strength",
    "Belt of Frost Giant Strength",
    "Belt of Stone Giant Strength",
    "Bracelet of Rock Magic",
    "Candle of Invocation",
    "Carpet of Flying 10ftx10ft",
    "Cloak of Arachnida",
    "Conch of Teleportation",
    "Crystal Ball",
    "Devastation Orb of Air",
    "Devastation Orb of Earth",
    "Devastation Orb of Fire",
    "Devastation Orb of Water",
    "Efreeti Bottle",
    "Figurine of Wondrous Power, Obsidian Steed",
    "Helm of Brilliance",
    "Horn of Valhalla, Bronze",
    "Horseshoes of a Zephyr",
    "Ingot of the Skold Rune",
    "Instrument of the Bards, Anstruth Harp",
    "Ioun Stone, Absorption",
    "Ioun Stone, Agility",
    "Ioun Stone, Fortitude",
    "Ioun Stone, Insight",
    "Ioun Stone, Intellect",
    "Ioun Stone, Leadership",
    "Ioun Stone, Strength",
    "Lords Ensemble",
    "Manual of Bodily Health",
    "Manual of Clay Golems",
    "Manual of Flesh Golems",
    "Manual of Gainful Exercise",
    "Manual of Iron Golems",
    "Manual of Quickness of Action",
    "Manual of Stone Golems",
    "Mirror of Life Trapping",
    "Navigation Orb",
    "Nolzur’s Marvelous Pigments",
    "Oil of Sharpness",
    "Pennant of Vind Rune",
    "Ring of Regeneration",
    "RIng of Shooting Stars",
    "Ring of Telekinesis",
    "Robe of Scintillating Colors",
    "Robe of Stars",
    "Rod of Absorption",
    "Rod of Alertness",
    "Rod of Security",
    "Rod of the Pact Keeper, +3",
    "Shard of the Ise Rune",
    "Spell Gem, Amber",
    "Spell Gem, Jade",
    "Spell Gem, Topaz",
    "Staff of Fire",
    "Staff of Frost",
    "Staff of Power",
    "Staff of Striking",
    "Staff of Thunder and Lightning",
    "Tome of Clear Thought",
    "Tome of Leadership and Influence",
    "Tome of Understanding",
    "Wand of Polymorph",
    "Wand of the War Mage, +3",
    "Absorbing Tattoo (T)",
    "Cauldron of Rebirth (T)",
    "Ghost Step Tattoo (T)",
    "Lifewell Tattoo (T)"
]

potions = [
    "Gaseous Form",
    "Giant Size",
    "Growth",
    "Heroism",
    "Hill Giant Strength",
    "Human Mind Control",
    "Invisibility",
    "Invulnerability",
    "Damage Resistance",
    "Longevity",
    "Mind Reading",
    "Poison",
    "Monster Mind Control",
    "Speed",
    "Stone Giant Strength",
    "Storm Giant Strength",
    "Supreme Healing",
    "Vitality",
    "Water Breathing"
]


